# Generated by Django 6.1 on 2026-09-02 13:12

import django.db.models.deletion
import invoices.models
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InvoiceBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_file', models.FileField(upload_to=invoices.models.upload_path)),
                ('original_filename', models.CharField(max_length=255)),
                ('total_rows', models.PositiveIntegerField(default=0)),
                ('valid_rows', models.PositiveIntegerField(default=0)),
                ('invalid_rows', models.PositiveIntegerField(default=0)),
                ('generated_count', models.PositiveIntegerField(default=0)),
                ('failed_count', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('UPLOADED', 'Uploaded'), ('PROCESSING', 'Processing'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='UPLOADED', max_length=20)),
                ('error_report', models.FileField(blank=True, null=True, upload_to=invoices.models.error_report_path)),
                ('error_summary', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='batches', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(db_index=True, max_length=50, unique=True)),
                ('invoice_date', models.DateField(db_index=True)),
                ('invoice_to', models.CharField(blank=True, default='', max_length=255)),
                ('supplier_name', models.CharField(db_index=True, max_length=255)),
                ('supplier_address', models.TextField(blank=True)),
                ('country', models.CharField(blank=True, max_length=100)),
                ('state', models.CharField(blank=True, max_length=100)),
                ('state_code', models.CharField(blank=True, max_length=10)),
                ('place_of_supply', models.CharField(blank=True, max_length=100)),
                ('supplier_gstin', models.CharField(blank=True, default='NA', max_length=20)),
                ('description', models.CharField(max_length=500)),
                ('hsn', models.CharField(blank=True, max_length=20, verbose_name='HSN/SAC')),
                ('quantity', models.DecimalField(decimal_places=2, default=Decimal('1'), max_digits=12)),
                ('total_value', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=16)),
                ('discount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=16)),
                ('taxable_value', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=16)),
                ('tax_type', models.CharField(choices=[('IGST', 'IGST'), ('CGST_SGST', 'CGST + SGST')], default='IGST', max_length=10)),
                ('tax_rate', models.DecimalField(decimal_places=3, default=Decimal('18'), max_digits=6)),
                ('tax_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=16)),
                ('cgst_rate', models.DecimalField(decimal_places=3, default=Decimal('0'), max_digits=6)),
                ('cgst_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=16)),
                ('sgst_rate', models.DecimalField(decimal_places=3, default=Decimal('0'), max_digits=6)),
                ('sgst_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=16)),
                ('igst_rate', models.DecimalField(decimal_places=3, default=Decimal('0'), max_digits=6)),
                ('igst_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=16)),
                ('freight', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=16)),
                ('insurance', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=16)),
                ('packing', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=16)),
                ('total', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=16)),
                ('amount_in_words', models.CharField(blank=True, max_length=500)),
                ('status', models.CharField(choices=[('GENERATED', 'Generated'), ('FAILED', 'Failed'), ('PENDING', 'Pending')], default='PENDING', max_length=20)),
                ('error_message', models.CharField(blank=True, max_length=500)),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='generated/pdf/')),
                ('docx_file', models.FileField(blank=True, null=True, upload_to='generated/docx/')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices', to=settings.AUTH_USER_MODEL)),
                ('batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='invoices.invoicebatch')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='invoicebatch',
            index=models.Index(fields=['-created_at'], name='invoices_in_created_542c8f_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['invoice_number'], name='invoices_in_invoice_e6b546_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['invoice_date'], name='invoices_in_invoice_087f87_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['supplier_name'], name='invoices_in_supplie_c6221b_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['batch'], name='invoices_in_batch_i_62a189_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['-created_at'], name='invoices_in_created_67cbdc_idx'),
        ),
    ]
