# Generated by Django 6.1 on 2026-10-01 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='ci_cd_test',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
    ]
