# Generated by Django 6.1 on 2026-10-01 06:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_add_ci_cd_test'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='ci_cd_test',
        ),
    ]
