# Generated by Django 6.1 on 2026-09-14 05:47

import django.db.models.deletion
import pdf_editor.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PdfBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255)),
                ('total_files', models.PositiveIntegerField(default=0)),
                ('processed_count', models.PositiveIntegerField(default=0)),
                ('failed_count', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('UPLOADED', 'Uploaded'), ('PROCESSING', 'Processing'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='UPLOADED', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pdf_batches', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PdfDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_file', models.FileField(upload_to=pdf_editor.models.original_pdf_path)),
                ('filename', models.CharField(max_length=255)),
                ('page_count', models.PositiveIntegerField(default=0)),
                ('has_extractable_text', models.BooleanField(default=True)),
                ('status', models.CharField(choices=[('UPLOADED', 'Uploaded'), ('READY', 'Ready'), ('SCANNED', 'Scanned / Image-based'), ('FAILED', 'Failed')], default='UPLOADED', max_length=20)),
                ('error_message', models.CharField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='pdf_editor.pdfbatch')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pdf_documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PdfVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_number', models.PositiveIntegerField()),
                ('file', models.FileField(upload_to=pdf_editor.models.version_pdf_path)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pdf_versions', to=settings.AUTH_USER_MODEL)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='pdf_editor.pdfdocument')),
            ],
            options={
                'ordering': ['document_id', 'version_number'],
            },
        ),
        migrations.CreateModel(
            name='PdfEditOperation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation_type', models.CharField(choices=[('REPLACE', 'Replace'), ('ADD', 'Add'), ('DELETE', 'Delete/Hide'), ('MOVE', 'Move')], max_length=10)),
                ('original_text', models.TextField(blank=True)),
                ('replacement_text', models.TextField(blank=True)),
                ('page', models.PositiveIntegerField(default=0)),
                ('coordinates', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pdf_edit_operations', to=settings.AUTH_USER_MODEL)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operations', to='pdf_editor.pdfdocument')),
                ('version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operations', to='pdf_editor.pdfversion')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='pdfdocument',
            name='current_version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='pdf_editor.pdfversion'),
        ),
        migrations.AddIndex(
            model_name='pdfbatch',
            index=models.Index(fields=['-created_at'], name='pdf_editor__created_f81669_idx'),
        ),
        migrations.AddIndex(
            model_name='pdfversion',
            index=models.Index(fields=['document', 'version_number'], name='pdf_editor__documen_ecd3a1_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='pdfversion',
            unique_together={('document', 'version_number')},
        ),
        migrations.AddIndex(
            model_name='pdfeditoperation',
            index=models.Index(fields=['document', '-created_at'], name='pdf_editor__documen_27e938_idx'),
        ),
        migrations.AddIndex(
            model_name='pdfdocument',
            index=models.Index(fields=['-created_at'], name='pdf_editor__created_20a12c_idx'),
        ),
        migrations.AddIndex(
            model_name='pdfdocument',
            index=models.Index(fields=['status'], name='pdf_editor__status_fa6572_idx'),
        ),
    ]
