# Generated by Django 6.1 on 2026-09-14 07:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdf_editor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pdfeditoperation',
            name='new_label',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='pdfeditoperation',
            name='new_separator',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='pdfeditoperation',
            name='old_label',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='pdfeditoperation',
            name='old_separator',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='pdfeditoperation',
            name='operation_type',
            field=models.CharField(choices=[('REPLACE', 'Replace'), ('ADD', 'Add'), ('DELETE', 'Delete/Hide'), ('MOVE', 'Move'), ('LABEL_EDIT', 'Label/Value Edit')], max_length=10),
        ),
        migrations.CreateModel(
            name='PdfField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page', models.PositiveIntegerField(default=0)),
                ('label', models.CharField(blank=True, max_length=255)),
                ('original_label', models.CharField(blank=True, max_length=255)),
                ('label_key', models.CharField(blank=True, db_index=True, max_length=255)),
                ('value', models.TextField(blank=True)),
                ('original_value', models.TextField(blank=True)),
                ('separator', models.CharField(blank=True, default=':', max_length=10)),
                ('original_separator', models.CharField(blank=True, default=':', max_length=10)),
                ('label_bbox', models.JSONField(blank=True, default=dict)),
                ('value_bbox', models.JSONField(blank=True, default=dict)),
                ('font', models.CharField(blank=True, max_length=100)),
                ('font_size', models.FloatField(default=10)),
                ('font_weight', models.CharField(blank=True, default='normal', max_length=10)),
                ('color', models.JSONField(blank=True, default=list)),
                ('confidence', models.CharField(choices=[('HIGH', 'High confidence'), ('MEDIUM', 'Needs review'), ('LOW', 'Needs review')], default='MEDIUM', max_length=10)),
                ('status', models.CharField(choices=[('DETECTED', 'Detected'), ('CONFIRMED', 'Confirmed'), ('REJECTED', 'Rejected'), ('MANUAL', 'Manual'), ('EDITED', 'Edited')], default='DETECTED', max_length=10)),
                ('is_detected', models.BooleanField(default=True)),
                ('is_manual', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='pdf_editor.pdfdocument')),
            ],
            options={
                'ordering': ['page', 'label'],
            },
        ),
        migrations.AddField(
            model_name='pdfeditoperation',
            name='field',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='operations', to='pdf_editor.pdffield'),
        ),
        migrations.AddIndex(
            model_name='pdffield',
            index=models.Index(fields=['document', 'page'], name='pdf_editor__documen_aad9ea_idx'),
        ),
        migrations.AddIndex(
            model_name='pdffield',
            index=models.Index(fields=['document', 'label_key'], name='pdf_editor__documen_5113be_idx'),
        ),
    ]
