# Generated by Django 6.1 on 2026-09-24 11:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdf_editor', '0002_pdfeditoperation_new_label_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PdfReplacementRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_type', models.CharField(choices=[('any', 'Any Value'), ('exact', 'Exact Match'), ('contains', 'Contains'), ('starts_with', 'Starts With'), ('ends_with', 'Ends With'), ('not_equal', 'Does Not Equal'), ('regex', 'Regex (Advanced)')], default='any', max_length=20)),
                ('current_value', models.CharField(blank=True, max_length=500)),
                ('case_sensitive', models.BooleanField(default=False)),
                ('whitespace_normalize', models.BooleanField(default=True)),
                ('change_label', models.BooleanField(default=False)),
                ('new_label', models.CharField(blank=True, max_length=255)),
                ('change_separator', models.BooleanField(default=False)),
                ('new_separator', models.CharField(blank=True, max_length=10)),
                ('new_value', models.CharField(blank=True, max_length=500)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='PdfReplacementRuleLabel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=255)),
                ('rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='labels', to='pdf_editor.pdfreplacementrule')),
            ],
        ),
        migrations.CreateModel(
            name='PdfReplacementRuleSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pdf_rule_sets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='pdfreplacementrule',
            name='rule_set',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rules', to='pdf_editor.pdfreplacementruleset'),
        ),
    ]
