# Generated by Django 6.1 on 2026-09-30 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdf_editor', '0003_pdfreplacementrule_pdfreplacementrulelabel_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pdffield',
            name='is_stacked',
            field=models.BooleanField(default=False),
        ),
    ]
