# Generated by Django 6.1 on 2026-09-30 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdf_editor', '0004_pdffield_is_stacked'),
    ]

    operations = [
        migrations.AddField(
            model_name='pdffield',
            name='label_color',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='pdffield',
            name='label_font',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='pdffield',
            name='label_font_size',
            field=models.FloatField(default=10),
        ),
        migrations.AddField(
            model_name='pdffield',
            name='label_font_weight',
            field=models.CharField(blank=True, default='normal', max_length=10),
        ),
    ]
