# Generated by Django 6.1 on 2026-09-02 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CompanySettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(default='VELLKO MEDIA PRIVATE LIMITED', max_length=255)),
                ('company_address', models.TextField(default='215- A, 2nd Floor, Chinar Incube Business Center, Hoshangabad Road, Bhopal, Madhya Pradesh, 462026')),
                ('gstin', models.CharField(default='23AAICV4798D1Z2', max_length=20, verbose_name='GSTIN')),
                ('state', models.CharField(default='Madhya Pradesh', max_length=100)),
                ('state_code', models.CharField(default='23', max_length=10)),
                ('place_of_supply', models.CharField(default='Madhya Pradesh', max_length=100)),
                ('country', models.CharField(default='India', max_length=100)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('website', models.CharField(blank=True, max_length=255)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='company/')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Company Settings',
                'verbose_name_plural': 'Company Settings',
            },
        ),
        migrations.CreateModel(
            name='InvoiceSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_title', models.CharField(default='Tax Invoice', max_length=100)),
                ('invoice_to', models.CharField(blank=True, default='', max_length=255)),
                ('footer_for_text', models.CharField(default='For VELLKO MEDIA PRIVATE', max_length=255)),
                ('authorized_signatory_text', models.CharField(default='Authorized Signatory', max_length=100)),
                ('reverse_charge_note', models.CharField(default='*Tax is payable on Reverse Charge Basis', max_length=255)),
                ('default_tax_rate', models.DecimalField(decimal_places=3, default=18, max_digits=6)),
                ('default_hsn', models.CharField(blank=True, default='998319', max_length=20)),
                ('currency', models.CharField(default='INR', max_length=10)),
                ('currency_symbol', models.CharField(default='₹', max_length=5)),
                ('amount_words_format', models.CharField(choices=[('currency', 'Currency style (Rupees ... and Paise Only)'), ('plain', 'Plain style (... Point XX)')], default='currency', max_length=10)),
                ('invoice_number_prefix', models.CharField(default='RCM-', max_length=20)),
                ('invoice_number_start', models.PositiveIntegerField(default=1)),
                ('invoice_number_padding', models.PositiveIntegerField(default=2)),
                ('rounding_precision', models.PositiveIntegerField(default=2)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Invoice Settings',
                'verbose_name_plural': 'Invoice Settings',
            },
        ),
        migrations.CreateModel(
            name='Signature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slot', models.PositiveSmallIntegerField(choices=[(1, 'Signature 1 (Director / Stamp)'), (2, 'Signature 2 (Authorized Signatory)')], unique=True)),
                ('label', models.CharField(blank=True, max_length=100)),
                ('image', models.ImageField(upload_to='signatures/')),
                ('is_active', models.BooleanField(default=True)),
                ('uploaded_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['slot'],
            },
        ),
    ]
